version: "3.9"

services:
  backend:
    build: ./backend
    container_name: springboot-backend
    ports:
      - "8080:8080"
    networks:
      - fullstack-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge